### ISSUE TITLE
[FEATURE REQUEST] CSV File Import

### ISSUE THREAD

**Issue by fmaida** [dnlzrgz/memotica#1]
Hi, your app looks great. Would you consider adding the ability to import whole decks from CSV files in a future upgrade, please?

Thank you very much, and best regards

**Comment by dnlzrgz** [comment]
Hi there! I'm currently working on this and will try to push the changes in a couple of days. However, for the moment, I will only support importing decks and flashcards that have been exported from memotica.

**Comment by fmaida** [comment]
Thank you ❤️ 

Can I also use a keyboard shortcut to confirm my knowledge of the question (wrong/good/easy)instead of clicking the corresponding button on the interface?
For example: "W", "G" and "E" or maybe "1", "2" and "3"?

![Schermata 2024-07-10 alle 11 31 50](https://github.com/dnlzrgz/memotica/assets/605017/a1bfa140-fb28-4a9c-a2e2-638c43091736)

**Comment by dnlzrgz** [comment]
Yes! That's something I will start working on soon. For the moment, I will close this issue since I just added the import and export sub-commands, and open a new issue with the request to add the keybindings to the review screen.
